SELECT PRODUCT_CODE, (PRICE * TOTAL) AS SALES
FROM PRODUCT AS A
JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTAL FROM OFFLINE_SALE GROUP BY PRODUCT_ID) AS B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE 

