SELECT A.PRODUCT_ID, PRODUCT_NAME, (PRICE * TOTAL) AS TOTAL_SALES
FROM FOOD_PRODUCT AS A
JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL FROM FOOD_ORDER WHERE PRODUCE_DATE LIKE '2022-05%' GROUP BY PRODUCT_ID) AS B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID
