SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (MAX_V - SIZE_OF_COLONY) AS YEAR_DEV, A.ID 
FROM ECOLI_DATA AS A
JOIN (SELECT MAX(SIZE_OF_COLONY) AS MAX_V, YEAR(DIFFERENTIATION_DATE) AS SUB_YEAR FROM ECOLI_DATA GROUP BY SUB_YEAR) AS B
ON YEAR(DIFFERENTIATION_DATE) = B.SUB_YEAR
ORDER BY YEAR, YEAR_DEV 
