SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A
JOIN FISH_NAME_INFO AS B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.LENGTH = (SELECT MAX(LENGTH) FROM FISH_INFO WHERE FISH_TYPE = A.FISH_TYPE)
ORDER BY A.ID

# SELECT I.ID, N.FISHNAME,I.LENGTH
# FROM FISHINFO AS I JOIN FISHNAMEINFO AS N
# ON I.FISHTYPE = N.FISHTYPE
# WHERE I.LENGTH = (SELECT MAX(LENGTH)
# FROM FISHINFO
# WHERE FISHTYPE=I.FISH_TYPE)
# ORDER BY I.ID;