SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A
JOIN FISH_NAME_INFO AS B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE LENGTH = (SELECT MAX(LENGTH) FROM FISH_INFO AS A2 WHERE A.FISH_TYPE = A2.FISH_TYPE)
ORDER BY A.ID