SELECT A.CATEGORY, MAX_P, PRODUCT_NAME
FROM FOOD_PRODUCT AS A
JOIN (SELECT CATEGORY, MAX(PRICE) AS MAX_P FROM FOOD_PRODUCT 
     WHERE CATEGORY IN ('과자', '국', '김치', '식용유') GROUP BY CATEGORY) AS B
ON A.CATEGORY = B.CATEGORY AND B.MAX_P = A.PRICE
ORDER BY MAX_P DESC